# operator templates
####################

# qif operator
qif_op:
  base: OperatorTemplate
  equations:
    - "v' = (v^2 + tau*J*s_in + eta + I_ext) / tau"
    - "s' = (spike-s)/tau_s"
    - "u_ltp' = -u_ltp / tau_ltp + spike"
    - "u_ltd' = -u_ltd / tau_ltd + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u_ltp: variable(0.05)
    u_ltd: variable(0.05)
    tau: 10.0
    J: 20.0
    tau_s: 6.0
    eta: 0.0
    tau_ltp: 200.0
    tau_ltd: 50.0
    I_ext: input(0.0)
    spike: input(0.0)
    s_in: input(0.0)

# edge operator
stdp_op:
  base: OperatorTemplate
  equations:
    - "w' = a_ltp*x_ltp*r_t - sqrt(w)*a_ltd*x_ltd*r_in"
    - "r_out = r_in*w"
  variables:
    r_out: output(0.0)
    w: variable(1.0)
    a_ltp: 0.1
    a_ltd: 0.05
    r_in: input(0.0)
    r_t: input(0.0)
    x_ltp: input(0.0)
    x_ltd: input(0.0)

# node templates
################

qif_pop:
  base: NodeTemplate
  operators:
    - qif_op

stdp_edge:
  base: EdgeTemplate
  operators:
    - stdp_op
