r"""
Adaptive-coupling Kuramoto: Δ-ramp microscopic simulations (data generation)
============================================================================

Slow HETEROGENEITY ramps of the microscopic adaptive Kuramoto network (full N×N), for both
adaptation rules G ∈ {cos, sin} and for μ ∈ {0.003, 0.03} at fixed K=1, γ=0.01 — the parameters of
the bifurcation diagrams in ``weight_variance_bifurcation_rules.py``, so the ramps can be read
directly against those Δ-bifurcation diagrams (μ<γ monostable, μ>γ bistable for cos).

Δ is stepped through ``np.arange(*delta_ramp)`` and held for `tau_d` (≫ 1/γ), with the network state
carried across steps to expose hysteresis. The frequencies are the Lorentzian quantiles scaled by the
current Δ (ω_i = Δ·tan(π(p_i−½))), so an oscillator keeps its rank as the heterogeneity changes:
  * FORWARD  ramp — Δ increasing (synchronized → asynchronous), IC θ_i = 0 (R = 1);
  * BACKWARD ramp — Δ decreasing (asynchronous → synchronized), IC θ_i ~ U(0,2π) (R ≈ 0).
Both start from UNIFORM weights A_ij = 1.

Records, at every `dts`, the coherence R(t), the mean weight Ā(t) and the weight variance V_A(t)
(off-diagonal), plus per-Δ-step averages over the last `meas_frac` of each hold. This is the HEAVY
part of the ramp pipeline; the cheap mean-field ramp is generated by
``weight_variance_ramp_meanfield.py`` (which imports the shared parameters/helpers from here).

Uses the numba kernel of ``weight_variance_rule_micro.py`` when available (~10× faster):
    PATH="$HOME/conda/envs/allen/bin:$PATH" python weight_variance_ramp_micro.py
"""

# --- shared library bootstrap (repo-root shared/) ---------------------------
import os, sys
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [_HERE, os.path.join(_HERE, "..", "shared")]
import data_paths as dp
# ---------------------------------------------------------------------------
import os
import numpy as np

import weight_variance_rule_micro as base                 # numba kernel + Lorentzian quantiles

HAS_NUMBA = base.HAS_NUMBA

CONFIG = dict(
    # model parameters — identical to weight_variance_bifurcation_rules.py
    K=1.0, gamma=0.01,
    mus=[0.003, 0.03],                 # μ<γ (monostable) and μ>γ (bistable for cos)
    rules=["cos", "sin"],              # symmetric / antisymmetric adaptation
    # the ramp
    delta_ramp=(0.05, 1.25, 0.1),      # ramped Δ values: np.arange(start, stop, step)
    delta_min=0.0, delta_max=1.2,      # Δ-range of the analytic branches (figures only)
    tau_d=2000.0,                      # dwell per Δ step (≫ 1/γ = 100, i.e. quasi-static weights)
    # network + Euler integration
    N=500, dt=0.05, dts=2.0, meas_frac=0.3, seed=22,
    out_dir=dp.KMO_ADAPTIVE,
    out_name="weight_variance_ramp_micro.npz",
)


def _dsteps(cfg, direction):
    """Δ values of the ramp, in the order they are visited."""
    ds = np.arange(*cfg["delta_ramp"])
    return ds[::-1] if direction == "bwd" else ds


def _abar_ss(delta, mu, g, K):
    """Upper (stable) synchronous-branch weight Ā* at heterogeneity Δ; 1 if no sync root."""
    b = 1.0 + mu / g
    disc = 0.25 * b ** 2 - 2.0 * mu * delta / (g * K)
    return 0.5 * b + np.sqrt(disc) if disc > 0 else 1.0


def _weight_moments(A):
    """(Ā, V_A) over the off-diagonal weights."""
    N = A.shape[0]
    n_off = N * N - N
    d = np.diag(A)
    s1 = A.sum() - d.sum()
    s2 = (A * A).sum() - (d * d).sum()
    Abar = s1 / n_off
    return Abar, s2 / n_off - Abar ** 2


# ════════════════════════════════════════════════════════════════════════════
#  microscopic Δ-ramp: full N×N adaptive network (Euler), state carried across steps
# ════════════════════════════════════════════════════════════════════════════
def micro_ramp(rule, mu, direction, cfg):
    """Ramp Δ through ``_dsteps``, holding each value for `tau_d`. Returns
    (t, R(t), Ā(t), V_A(t), R per step, V_A/Ā² per step)."""
    N, K, g, dt = cfg["N"], cfg["K"], cfg["gamma"], cfg["dt"]
    n_hold = int(cfg["tau_d"] / dt)
    rec = max(1, int(cfg["dts"] / dt))
    rng = np.random.default_rng(cfg["seed"])
    quant = base.lorentzian_quantiles(N, 1.0)             # unit-Δ quantiles; ω = Δ · quant
    c_cos = 1.0 if rule == "cos" else 0.0

    if direction == "fwd":                                # Δ increasing: start synchronized
        theta = np.zeros(N)
    else:                                                 # Δ decreasing: start incoherent
        theta = rng.uniform(0.0, 2.0 * np.pi, N)
    A = np.ones((N, N))                                   # uniform initial weights
    theta = np.ascontiguousarray(theta)

    rec_mask = np.zeros(n_hold, dtype=np.bool_)
    rec_mask[::rec] = True
    n_rec = int(rec_mask.sum())
    m0 = int((1.0 - cfg["meas_frac"]) * n_rec)            # measurement window of each hold

    tcur, T, Rt, Abt, VAt, Rpts, VRpts = 0.0, [], [], [], [], [], []
    for D in _dsteps(cfg, direction):
        omega = np.ascontiguousarray(D * quant)
        Rs, Abars, VAs = (np.empty(n_rec) for _ in range(3))
        if HAS_NUMBA:
            base._simulate_numba(theta, A, omega, float(K), float(mu), float(g), float(dt),
                                 int(n_hold), rec_mask, c_cos, Rs, Abars, VAs)
        else:
            KinvN, ridx = K / N, 0
            for k in range(n_hold):
                e = np.exp(1j * theta)
                if rec_mask[k]:
                    Abar, VA = _weight_moments(A)
                    Rs[ridx], Abars[ridx], VAs[ridx] = np.abs(e.mean()), Abar, VA
                    ridx += 1
                gph = np.conj(e)[:, None] * e[None, :]    # e^{i(θ_j − θ_i)}
                G = np.real(gph) if rule == "cos" else np.imag(gph)
                theta = theta + dt * (omega + KinvN * np.imag(np.conj(e) * (A @ e)))
                A = A + dt * (mu * G + g * (1.0 - A))
        T.append(tcur + np.arange(n_rec) * cfg["dts"])
        Rt.append(Rs.copy()); Abt.append(Abars.copy()); VAt.append(VAs.copy())
        Rpts.append(float(Rs[m0:].mean()))
        VRpts.append(float((VAs[m0:] / Abars[m0:] ** 2).mean()))
        tcur += cfg["tau_d"]
    return (np.concatenate(T), np.concatenate(Rt), np.concatenate(Abt), np.concatenate(VAt),
            np.array(Rpts), np.array(VRpts))


# ════════════════════════════════════════════════════════════════════════════
#  main
# ════════════════════════════════════════════════════════════════════════════
def main(cfg=CONFIG):
    rules, mus = cfg["rules"], cfg["mus"]
    deltas = np.arange(*cfg["delta_ramp"])
    nr, nm, nd = len(rules), len(mus), deltas.size
    print(f"micro Δ-ramp [{'numba' if HAS_NUMBA else 'numpy'}] — K={cfg['K']}, γ={cfg['gamma']}, "
          f"μ={mus}, rules={rules}, N={cfg['N']}, {nd} Δ-steps ∈ {np.round(deltas, 2)} "
          f"× τ_d={cfg['tau_d']:g}")

    Tm = Rm = Abm = VAm = Rp_m = VRp_m = None
    for ri, rule in enumerate(rules):
        for i, mu in enumerate(mus):
            for di, d in enumerate(("fwd", "bwd")):
                tm, rm, abm, vam, rpm, vrpm = micro_ramp(rule, mu, d, cfg)
                if Rm is None:
                    Tm = tm
                    Rm, Abm, VAm = (np.full((nr, nm, 2, tm.size), np.nan) for _ in range(3))
                    Rp_m, VRp_m = (np.full((nr, nm, 2, nd), np.nan) for _ in range(2))
                Rm[ri, i, di], Abm[ri, i, di], VAm[ri, i, di] = rm, abm, vam
                asc = slice(None) if d == "fwd" else slice(None, None, -1)   # store ascending in Δ
                Rp_m[ri, i, di], VRp_m[ri, i, di] = rpm[asc], vrpm[asc]
                print(f"  G={rule:<4} μ={mu:<6g} {d}: R {rm[0]:.3f}→{rm[-1]:.3f}  "
                      f"Ā(end)={abm[-1]:.3f}  V_A/Ā²(end)={vam[-1] / abm[-1] ** 2:.4f}")

    os.makedirs(cfg["out_dir"], exist_ok=True)
    out = os.path.join(cfg["out_dir"], cfg["out_name"])
    np.savez(out, rules=np.array(rules), mus=np.asarray(mus, float), deltas=deltas, n_ramp=nd,
             Tm=Tm, Rm=Rm, Abm=Abm, VAm=VAm, Rp_m=Rp_m, VRp_m=VRp_m,
             K=cfg["K"], gamma=cfg["gamma"], delta_min=cfg["delta_min"], delta_max=cfg["delta_max"],
             tau_d=cfg["tau_d"], N=cfg["N"], dt=cfg["dt"], dts=cfg["dts"], seed=cfg["seed"])
    print(f"[saved] {out}  (Rm {Rm.shape}, directions 0=fwd/1=bwd)")


if __name__ == "__main__":
    main()
